import 'package:flutter/material.dart';
import 'package:mossala_mobile/widgets/app_bar.dart';
import 'package:mossala_mobile/widgets/cards.dart';

class WorkerScreen extends StatefulWidget {
  const WorkerScreen({super.key});

  @override
  State<WorkerScreen> createState() => _WorkerScreenState();
}

class _WorkerScreenState extends State<WorkerScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: appBarWidget("Prestataire"),
      body: SingleChildScrollView(
        padding: EdgeInsets.symmetric(horizontal: 15),
        child: Column(
          spacing: 10,
          children: [
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
            WorkerCardView(),
          ],
        ),
      ),
    );
  }
}